services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.neural-backend.rule=Host(`neural-api.evhsync.com`)
      - traefik.http.routers.neural-backend.tls=true
      - traefik.http.routers.neural-backend.tls.certresolver=letsencrypt
      - traefik.http.services.neural-backend.loadbalancer.server.port=5000

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://neural-api.evhsync.com
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.neural-frontend.rule=Host(`neural.evhsync.com`)
      - traefik.http.routers.neural-frontend.tls=true
      - traefik.http.routers.neural-frontend.tls.certresolver=letsencrypt
      - traefik.http.services.neural-frontend.loadbalancer.server.port=80